require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/armors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Armor. As you add validations to Armor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Armor.create! valid_attributes
      get armors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      armor = Armor.create! valid_attributes
      get armor_url(armor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_armor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      armor = Armor.create! valid_attributes
      get edit_armor_url(armor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Armor" do
        expect {
          post armors_url, params: { armor: valid_attributes }
        }.to change(Armor, :count).by(1)
      end

      it "redirects to the created armor" do
        post armors_url, params: { armor: valid_attributes }
        expect(response).to redirect_to(armor_url(Armor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Armor" do
        expect {
          post armors_url, params: { armor: invalid_attributes }
        }.to change(Armor, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post armors_url, params: { armor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested armor" do
        armor = Armor.create! valid_attributes
        patch armor_url(armor), params: { armor: new_attributes }
        armor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the armor" do
        armor = Armor.create! valid_attributes
        patch armor_url(armor), params: { armor: new_attributes }
        armor.reload
        expect(response).to redirect_to(armor_url(armor))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        armor = Armor.create! valid_attributes
        patch armor_url(armor), params: { armor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested armor" do
      armor = Armor.create! valid_attributes
      expect {
        delete armor_url(armor)
      }.to change(Armor, :count).by(-1)
    end

    it "redirects to the armors list" do
      armor = Armor.create! valid_attributes
      delete armor_url(armor)
      expect(response).to redirect_to(armors_url)
    end
  end
end
