require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/combat_equipments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CombatEquipment. As you add validations to CombatEquipment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CombatEquipment.create! valid_attributes
      get combat_equipments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      combat_equipment = CombatEquipment.create! valid_attributes
      get combat_equipment_url(combat_equipment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_combat_equipment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      combat_equipment = CombatEquipment.create! valid_attributes
      get edit_combat_equipment_url(combat_equipment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CombatEquipment" do
        expect {
          post combat_equipments_url, params: { combat_equipment: valid_attributes }
        }.to change(CombatEquipment, :count).by(1)
      end

      it "redirects to the created combat_equipment" do
        post combat_equipments_url, params: { combat_equipment: valid_attributes }
        expect(response).to redirect_to(combat_equipment_url(CombatEquipment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CombatEquipment" do
        expect {
          post combat_equipments_url, params: { combat_equipment: invalid_attributes }
        }.to change(CombatEquipment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post combat_equipments_url, params: { combat_equipment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested combat_equipment" do
        combat_equipment = CombatEquipment.create! valid_attributes
        patch combat_equipment_url(combat_equipment), params: { combat_equipment: new_attributes }
        combat_equipment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the combat_equipment" do
        combat_equipment = CombatEquipment.create! valid_attributes
        patch combat_equipment_url(combat_equipment), params: { combat_equipment: new_attributes }
        combat_equipment.reload
        expect(response).to redirect_to(combat_equipment_url(combat_equipment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        combat_equipment = CombatEquipment.create! valid_attributes
        patch combat_equipment_url(combat_equipment), params: { combat_equipment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested combat_equipment" do
      combat_equipment = CombatEquipment.create! valid_attributes
      expect {
        delete combat_equipment_url(combat_equipment)
      }.to change(CombatEquipment, :count).by(-1)
    end

    it "redirects to the combat_equipments list" do
      combat_equipment = CombatEquipment.create! valid_attributes
      delete combat_equipment_url(combat_equipment)
      expect(response).to redirect_to(combat_equipments_url)
    end
  end
end
