require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/counters", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Counter. As you add validations to Counter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Counter.create! valid_attributes
      get counters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      counter = Counter.create! valid_attributes
      get counter_url(counter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_counter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      counter = Counter.create! valid_attributes
      get edit_counter_url(counter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Counter" do
        expect {
          post counters_url, params: { counter: valid_attributes }
        }.to change(Counter, :count).by(1)
      end

      it "redirects to the created counter" do
        post counters_url, params: { counter: valid_attributes }
        expect(response).to redirect_to(counter_url(Counter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Counter" do
        expect {
          post counters_url, params: { counter: invalid_attributes }
        }.to change(Counter, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post counters_url, params: { counter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested counter" do
        counter = Counter.create! valid_attributes
        patch counter_url(counter), params: { counter: new_attributes }
        counter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the counter" do
        counter = Counter.create! valid_attributes
        patch counter_url(counter), params: { counter: new_attributes }
        counter.reload
        expect(response).to redirect_to(counter_url(counter))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        counter = Counter.create! valid_attributes
        patch counter_url(counter), params: { counter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested counter" do
      counter = Counter.create! valid_attributes
      expect {
        delete counter_url(counter)
      }.to change(Counter, :count).by(-1)
    end

    it "redirects to the counters list" do
      counter = Counter.create! valid_attributes
      delete counter_url(counter)
      expect(response).to redirect_to(counters_url)
    end
  end
end
