require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/proprieties", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Propriety. As you add validations to Propriety, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Propriety.create! valid_attributes
      get proprieties_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      propriety = Propriety.create! valid_attributes
      get propriety_url(propriety)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_propriety_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      propriety = Propriety.create! valid_attributes
      get edit_propriety_url(propriety)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Propriety" do
        expect {
          post proprieties_url, params: { propriety: valid_attributes }
        }.to change(Propriety, :count).by(1)
      end

      it "redirects to the created propriety" do
        post proprieties_url, params: { propriety: valid_attributes }
        expect(response).to redirect_to(propriety_url(Propriety.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Propriety" do
        expect {
          post proprieties_url, params: { propriety: invalid_attributes }
        }.to change(Propriety, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post proprieties_url, params: { propriety: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested propriety" do
        propriety = Propriety.create! valid_attributes
        patch propriety_url(propriety), params: { propriety: new_attributes }
        propriety.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the propriety" do
        propriety = Propriety.create! valid_attributes
        patch propriety_url(propriety), params: { propriety: new_attributes }
        propriety.reload
        expect(response).to redirect_to(propriety_url(propriety))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        propriety = Propriety.create! valid_attributes
        patch propriety_url(propriety), params: { propriety: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested propriety" do
      propriety = Propriety.create! valid_attributes
      expect {
        delete propriety_url(propriety)
      }.to change(Propriety, :count).by(-1)
    end

    it "redirects to the proprieties list" do
      propriety = Propriety.create! valid_attributes
      delete propriety_url(propriety)
      expect(response).to redirect_to(proprieties_url)
    end
  end
end
